# Streamlit Cloud Secrets Template
# Copy this to Streamlit Cloud secrets section

[openai]
api_key = "your_openai_api_key_here"
base_url = ""

[anthropic]
api_key = "your_anthropic_api_key_here"

# Optional: Search API keys
[brave]
api_key = "your_brave_search_api_key_here"

[bocha]
api_key = "your_bocha_api_key_here"