[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#1e293b"
textColor = "#ffffff"

[browser]
gatherUsageStats = false